allowBuilds:
  esbuild: true
  '@parcel/watcher': true
  unrs-resolver: true

# Sett minimumReleaseAge for å unngå at pakker som nylig er publisert (< 7 dager) blir brukt i byggene.
# Sikkerhetstiltak for å unngå at vi bruker pakker som nylig er publisert og som potensielt kan være ondsinnede eller ustabile.
minimumReleaseAge: 10080 # 7 dager

minimumReleaseAgeExclude:
  - "@navikt/*"
