version: "3.9"
services:
  backend:
    image: ${IMAGE}
    build:
      context: .
      target: production
      dockerfile: ./server/Dockerfile
      args:
        NODE_ENV: production
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    restart: always


