version: "3.9"
services:
  backend:
    build:
      context: .
      target: dev
      dockerfile: server/Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./server:/home/node/app/server/
    expose:
      - 8080
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      target: dev
      dockerfile: client/Dockerfile
      args:
        NODE_ENV: development
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./client:/home/node/app/client
      - /home/node/app/client/node_modules


