version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: "lydia-user"
      POSTGRES_PASSWORD: "lydia-password"
      POSTGRES_DB: "lydia-password"
  api:
    image: ghcr.io/navikt/lydia-api:385778c72097cbcad7dccf785d7d439e5bdc0a1c
    ports:
      - "3333:8080"
    depends_on:
      - postgres
    environment:
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_USERNAME: "lydia-user"
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_PASSWORD: "lydia-password"
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_DATABASE: "lydia-db"
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_HOST: localhost
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_PORT: 5432
      AZURE_APP_CLIENT_ID: "lydia-api-client-id"
      AZURE_OPENID_CONFIG_JWKS_URI: "TODO FIX ME"
      AZURE_OPENID_CONFIG_ISSUER: "TODO FIX ME"
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.4.2
    ports:
      - "7654:8080"
    hostname: host.docker.internal
  frackend:
    build:
      context: .
      target: local
      dockerfile: server/Dockerfile
      args:
        NODE_ENV: development
    volumes: # For hot reloading av server-ressurser
      - ./server:/home/node/app/server/
    expose:
      - 8080
    ports:
      - "8080:8080"
  frontend:
    build:
      context: .
      target: local
      dockerfile: client/Dockerfile
      args:
        NODE_ENV: development
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes: # For hot reloading av klient-ressurser
      - ./client:/home/node/app/client
      - /home/node/app/client/node_modules
