services:
  postgres:
    image: postgres:14
#    build:
#      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  authserver:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.1
    hostname: host.docker.internal
    environment:
      TZ: Europe/Oslo
      SERVER_PORT: 6969
      JSON_CONFIG: "{\"interactiveLogin\":true,\"tokenCallbacks\":[{\"issuerId\":\"azure\",\"tokenExpiry\":3600,\"requestMappings\":[{\"requestParam\":\"grant_type\",\"claims\":{\"aud\":[\"lydia-api\"],\"NAVident\":\"Z123456\",\"groups\":[\"ensuperbrukerGroupId\"]}}]}]}"
    ports:
      - 6969:6969

  zookeeper:
    container_name: zookeeper
    image: kymeric/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://zookeeper:2181" ]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka:
    image: kymeric/cp-kafka
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 9093:9093
      - 9092:9092
    environment:
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: false
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,BROKER://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      #      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: Long.MAX_VALUE
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,BROKER://kafka:9092
      TZ: Europe/Oslo

#  control-center:
#    container_name: control-center
#    image: confluentinc/cp-enterprise-control-center:7.2.1
#    depends_on:
#      - kafka
#    ports:
#      - 9021:9021
#    environment:
#      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
#      CONTROL_CENTER_REPLICATION_FACTOR: 1
#      PORT: 9021

  backend:
    platform: linux/amd64
    image: ghcr.io/navikt/lydia-api:latest
    depends_on:
      - postgres
#      - kafka
      - authserver
    ports:
      - 8080:8080
      - 5005:5005
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://backend:8080/internal/isready" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      # Postgres env
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_HOST: postgres
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_PORT: 5432
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_USERNAME: postgres
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_PASSWORD: test
      NAIS_DATABASE_LYDIA_API_LYDIA_API_DB_DATABASE: postgres
      # Authserver env
      AZURE_APP_CLIENT_ID: lydia-api
      AZURE_OPENID_CONFIG_ISSUER: http://host.docker.internal:6969/azure
      AZURE_OPENID_CONFIG_JWKS_URI: http://host.docker.internal:6969/azure/jwks
      FIA_SUPERBRUKER_GROUP_ID: ensuperbrukerGroupId
      FIA_SAKSBEHANDLER_GROUP_ID: ensaksbehandlerGroupId
      FIA_LESETILGANG_GROUP_ID: enlesetilgangGroupId
      TEAM_PIA_GROUP_ID: enTeamPiaGroupId
      # Kafka env
      KAFKA_BROKERS: "BROKER://kafka:9092,PLAINTEXT://kafka:9092"
      KAFKA_TRUSTSTORE_PATH: ""
      KAFKA_KEYSTORE_PATH: ""
      KAFKA_CREDSTORE_PASSWORD: ""
      STATISTIKK_TOPIC: arbeidsgiver.sykefravarsstatistikk-v1
      IA_SAK_HENDELSE_TOPIC: pia.ia-sak-hendelse-v1
      IA_SAK_TOPIC: pia.ia-sak-v1
      BRREG_OPPDATERING_TOPIC: pia.brreg-oppdatering
      # Backend spesifikk env
      BRREG_UNDERENHET_URL: /brregmock/enhetsregisteret/api/underenheter/lastned
      CONSUMER_LOOP_DELAY: 1
      SSB_NARINGS_URL: /naringmock/api/klass/v1/30/json
      NAIS_CLUSTER_NAME: "lokal"
      # Spesifikk for remote debugging
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-cache:/data
  wonderwall:
    image: ghcr.io/nais/wonderwall:latest
    depends_on:
      - authserver
    ports:
      - "2222:2222"
    environment:
      WONDERWALL_OPENID_CLIENT_ID: "lydia-api"
      WONDERWALL_OPENID_CLIENT_JWK: '{"p":"_xCPvqs85ZZVg460Qfot26rQoNRPTOVDo5p4nqH3ep6BK_5TvoU5LFXd26W-1V1Lc5fcvvftClPOT201xgat4DVtliNtoc8od_tWr190A3AzbsAVFOx0nKa5uhLBxP9SsPM84llp6PXF6QTMGFiPYuoLDaQQqL1K4BbHq3ZzF2M","kty":"RSA","q":"7QLqW75zkfSDrn5rMoF50WXyB_ysNx6-2SvaXKGXaOn80IR7QW5vwkleJnsdz_1kr04rJws2p4HBJjUFfSJDi1Dapj7tbIwb0a1szDs6Y2fAa3DlzgXZCkoE2TIrW6UITgs14pI_a7RasclE71FpoZ78XNBvj3NmZugkNLBvRjs","d":"f7aT4poed8uKdcSD95mvbfBdb6X-M86d99su0c390d6gWwYudeilDugH9PMwqUeUhY0tdaRVXr6rDDIKLSE-uEyaYKaramev0cG-J_QWYJU2Lx-4vDGNHAE7gC99o1Ee_LXqMDCBawMYyVcSWx7PxGQfzhSsARsAIbkarO1sg9zsqPS4exSMbK8wyCTPgRbnkB32_UdZSGbdSib1jSYyyoAItZ8oZHiltVsZIlA97kS4AGPtozde043NC7Ik0uEzgB5qJ_tR7vW8MfDrBj6da2NrLh0UH-q28dooBO1vEu0rvKZIescXYk9lk1ZakHhhpZaLykDOGzxCpronzP3_kQ","e":"AQAB","use":"sig","qi":"9kMIR6pEoiwN3M6O0n8bnh6c3KbLMoQQ1j8_Zyir7ZIlmRpWYl6HtK0VnD88zUuNKTrQa7-jfE5uAUa0PubzfRqybACb4S3HIAuSQP00_yCPzCSRrbpGRDFqq-8eWVwI9VdiN4oqkaaWcL1pd54IDcHIbfk-ZtNtZgsOlodeRMo","dp":"VUecSAvI2JpjDRFxg326R2_dQWi6-uLMsq67FY7hx8WnOqZWKaUxcHllLENGguAmkgd8bv1F6-YJXNUO3Z7uE8DJWyGNTkSNK1CFsy0fBOdGywi-A7jrZFT6VBRhZRRY-YDaInPyzUkfWsGX26wAhPnrqCvqxgBEQJhdOh7obDE","alg":"RS256","dq":"7EUfw92T8EhEjUrRKkQQYEK0iGnGdBxePLiOshEUky3PLT8kcBHbr17cUJgjHBiKqofOVNnE3i9nkOMCWcAyfUtY7KmGndL-WIP-FYplpnrjQzgEnuENgEhRlQOCXZWjNcnPKdKJDqF4WAtAgSIznz6SbSQMUoDD8IoyraPFCck","n":"7CU8tTANiN6W_fD9SP1dK2vQvCkf7-nwvBYe5CfANV0_Bb0ZmQb77FVVsl1beJ7EYLz3cJmL8Is1RCHKUK_4ydqihNjEWTyZiQoj1i67pkqk_zRvfQa9raZR4uZbuBxx7dWUoPC6fFH2F_psAlHW0zf90fsLvhB6Aqq3uvO7XXqo8qNl9d_JSG0Rg_2QUYVb0WKmPVbbhgwtkFu0Tyuev-VZ9IzTbbr5wmZwEUVY7YAi73pDJkcZt5r2WjOF_cuIXe-O2vwbOrRgmJfHO9--mVLdATnEyrb6q2oy_75h6JjP-R4-TD1hyoFFoE2gmj-kSS6Z_Gggljs3Aw7--Nh10Q"}'
      WONDERWALL_OPENID_WELL_KNOWN_URL: http://host.docker.internal:6969/azure/.well-known/openid-configuration
      WONDERWALL_INGRESS: http://localhost:2222
      WONDERWALL_BIND_ADDRESS: 0.0.0.0:2222
      WONDERWALL_UPSTREAM_HOST: frontend:5173
      WONDERWALL_AUTO_LOGIN: true
    restart: on-failure

  frackend:
    build:
      context: server
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
      - redis
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NAIS_CLUSTER_NAME: dev
      SESSION_SECRET: secret
      OBO_TOKEN_ENC_KEY: bogus
      NAIS_NAMESPACE: pia
      LYDIA_API_URI: http://backend:8080
      SERVER_PORT: 3000
      AZURE_OPENID_CONFIG_JWKS_URI: http://host.docker.internal:6969/azure/jwks
      AZURE_APP_CLIENT_ID: lydia-api
      AZURE_APP_CLIENT_SECRET: secret
      AZURE_OPENID_CONFIG_ISSUER: http://host.docker.internal:6969/azure
      AZURE_OPENID_CONFIG_TOKEN_ENDPOINT: http://host.docker.internal:6969/azure/token

  frontend:
    build:
      context: client
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173


volumes:
  postgres-data:
  redis-cache:
