version: "3.9"
services:
  backend:
    build:
      context: .
      target: production
      dockerfile: ./server/Dockerfile
      args:
        NODE_ENV: production
    expose:
      - 8080
    ports:
      - "8080:8080"


