apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "lydia-radgiver-frontend"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  liveness:
    path: "/internal/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi
  prometheus:
    enabled: true
    path: "/metrics"
  accessPolicy:
    outbound:
      rules:
        - application: lydia-api
  ingresses: 
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}