apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "lydia-radgiver-frontend"
  namespace: "pia"
  labels:
    "team": "pia"
spec:
  image: {{image}}
  liveness:
    path: "/internal/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi
  prometheus:
    enabled: true
    path: "/metrics"
  accessPolicy:
    outbound:
      rules:
        - application: lydia-api
        - application: fia-radgiver-frontend-redis
      external:
        - host: {{lydia-api.ingress}}
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: {{fiaSuperbrukerGroup}}
          - id: {{fiaSaksbehandlerGroup}}
          - id: {{fiaLesetilgangGroup}}
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
  env:
    - name: LYDIA_API_URI
      value: http://lydia-api
    - name: REDIS_HOST
      value: fia-radgiver-frontend-redis.pia.svc.cluster.local
    - name: REDIS_PORT
      value: "6379"
    - name: FIA_SUPERBRUKER_GROUP_ID
      value: {{fiaSuperbrukerGroup}}
    - name: FIA_SAKSBEHANDLER_GROUP_ID
      value: {{fiaSaksbehandlerGroup}}
    - name: FIA_LESETILGANG_GROUP_ID
      value: {{fiaLesetilgangGroup}}
  envFrom:
    - secret: fia-redis
    - secret: fia-frackend
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
