apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "https://fia.ansatt.nav.no/$1"
    prometheus.io/scrape: "false"
  labels:
    app: lydia-radgiver-frontend
    team: pia
  name: prod-redirect-fia-ekstern-til-ansatt
  namespace: pia
spec:
  ingressClassName: nais-ingress-external
  rules:
    - host: fia.nav.no
      http:
        paths:
          - backend:
              service:
                name: lydia-radgiver-frontend
                port:
                  number: 80
            path: /(.*)
            pathType: ImplementationSpecific
