import { IASak } from "../src/domenetyper/domenetyper";
import { IaSakProsess } from "../src/domenetyper/iaSakProsess";
import { Spørreundersøkelse } from "../src/domenetyper/spørreundersøkelse";
import { SpørreundersøkelseResultat } from "../src/domenetyper/spørreundersøkelseResultat";
import { Virksomhet } from "../src/domenetyper/virksomhet";

export const dummyVirksomhet: Virksomhet = {
    orgnr: "123459876",
    navn: "SPENSTIG KATTEDYR",
    adresse: ["adresse"],
    postnummer: "1234",
    poststed: "POSTSTED",
    næring: {
        navn: "Jordbruk, tilhør. tjenester, jakt",
        kode: "01",
    },
    næringsundergruppe1: {
        navn: "Dyrking av ris",
        kode: "01.120",
    },
    næringsundergruppe2: {
        navn: "Utøvende kunstnere og underholdningsvirksomhet innen scenekunst",
        kode: "90.012",
    },
    næringsundergruppe3: {
        navn: "Bedriftsrådgivning og annen administrativ rådgivning",
        kode: "70.220",
    },
    bransje: null,
    sektor: "Statlig forvaltning",
    status: "AKTIV",
    aktivtSaksnummer: "01K5BFZM3JMXRM1N5682YG1WGF",
};
export const dummyIaSak: IASak = {
    saksnummer: "01K5BFZM3JMXRM1N5682YG1WGF",
    orgnr: "123459876",
    opprettetTidspunkt: new Date("2025-09-17T09:27:09.682Z"),
    opprettetAv: "S54321",
    endretTidspunkt: new Date("2025-09-17T09:27:09.776Z"),
    endretAv: "X12345",
    endretAvHendelseId: "01K5BFZM6GSQYJ0904B75G0K3R",
    eidAv: "X12345",
    status: "VI_BISTÅR",
    gyldigeNesteHendelser: [
        {
            saksHendelsestype: "TA_EIERSKAP_I_SAK",
            gyldigeÅrsaker: [],
        },
    ],
    lukket: false,
};
export const dummySamarbeid: IaSakProsess = {
    id: 3,
    saksnummer: "01K5BFZM3JMXRM1N5682YG1WGF",
    navn: "Avdeling Pusekatt",
    status: "AKTIV",
    sistEndret: new Date("2025-09-17T09:27:09.758Z"),
    opprettet: new Date("2025-09-17T09:27:09.758Z"),
};
export const dummySpørreundersøkelseliste: Spørreundersøkelse[] = [
    {
        id: "0be2f07b-6df3-46db-b187-79760599dd19",
        samarbeidId: 3,
        status: "AVSLUTTET",
        publiseringStatus: "IKKE_PUBLISERT",
        opprettetAv: "X12345",
        type: "BEHOVSVURDERING",
        opprettetTidspunkt: new Date("2025-09-17T09:27:12.408Z"),
        endretTidspunkt: new Date("2025-09-17T09:27:12.875Z"),
        påbegyntTidspunkt: new Date("2025-09-17T09:27:12.424Z"),
        publisertTidspunkt: null,
        fullførtTidspunkt: new Date("2025-09-17T09:27:12.875Z"),
        gyldigTilTidspunkt: new Date("2025-09-18T09:27:12.408Z"),
        harMinstEttResultat: true,
    },
    {
        id: "cfe2aff5-929f-4a1e-b2e7-0fd44038fea1",
        samarbeidId: 3,
        status: "AVSLUTTET",
        publiseringStatus: "OPPRETTET",
        opprettetAv: "X12345",
        type: "BEHOVSVURDERING",
        opprettetTidspunkt: new Date("2025-09-17T09:27:10.782Z"),
        endretTidspunkt: new Date("2025-09-17T09:27:12.389Z"),
        påbegyntTidspunkt: new Date("2025-09-17T09:27:10.798Z"),
        publisertTidspunkt: null,
        fullførtTidspunkt: new Date("2025-09-17T09:27:12.389Z"),
        gyldigTilTidspunkt: new Date("2025-09-18T09:27:10.782Z"),
        harMinstEttResultat: true,
    },
    {
        id: "2f75a5ea-7ad9-46b5-b4e9-37cd167e7958",
        samarbeidId: 3,
        status: "AVSLUTTET",
        publiseringStatus: "IKKE_PUBLISERT",
        opprettetAv: "X12345",
        type: "BEHOVSVURDERING",
        opprettetTidspunkt: new Date("2025-09-17T09:27:10.165Z"),
        endretTidspunkt: new Date("2025-09-17T09:27:10.767Z"),
        påbegyntTidspunkt: new Date("2025-09-17T09:27:10.184Z"),
        publisertTidspunkt: null,
        fullførtTidspunkt: new Date("2025-09-17T09:27:10.767Z"),
        gyldigTilTidspunkt: new Date("2025-09-18T09:27:10.165Z"),
        harMinstEttResultat: false,
    },
    {
        id: "dd583280-6e81-4f3b-a110-f28d095e32e0",
        samarbeidId: 3,
        status: "AVSLUTTET",
        publiseringStatus: "IKKE_PUBLISERT",
        opprettetAv: "X12345",
        type: "BEHOVSVURDERING",
        opprettetTidspunkt: new Date("2025-09-17T09:27:09.912Z"),
        endretTidspunkt: new Date("2025-09-17T09:27:10.143Z"),
        påbegyntTidspunkt: new Date("2025-09-17T09:27:09.935Z"),
        publisertTidspunkt: null,
        fullførtTidspunkt: new Date("2025-09-17T09:27:10.143Z"),
        gyldigTilTidspunkt: new Date("2025-09-18T09:27:09.912Z"),
        harMinstEttResultat: false,
    },
    {
        id: "dd583280-6e81-4f3b-a110-f28d095e32e1",
        samarbeidId: 3,
        status: "AVSLUTTET",
        publiseringStatus: "IKKE_PUBLISERT",
        opprettetAv: "X12345",
        type: "EVALUERING",
        opprettetTidspunkt: new Date("2025-09-17T09:27:09.912Z"),
        endretTidspunkt: new Date("2025-09-17T09:27:10.143Z"),
        påbegyntTidspunkt: new Date("2025-09-17T09:27:09.935Z"),
        publisertTidspunkt: null,
        fullførtTidspunkt: new Date("2025-09-17T09:27:10.143Z"),
        gyldigTilTidspunkt: new Date("2025-09-18T09:27:09.912Z"),
        harMinstEttResultat: false,
    },
    {
        id: "33ad219d-d864-44e5-ad53-6d7c7e58d834",
        samarbeidId: 3,
        status: "PÅBEGYNT",
        publiseringStatus: "IKKE_PUBLISERT",
        opprettetAv: "X12345",
        type: "BEHOVSVURDERING",
        opprettetTidspunkt: new Date("2025-09-17T09:27:09.862Z"),
        endretTidspunkt: new Date("2025-09-17T09:27:09.886Z"),
        påbegyntTidspunkt: new Date("2025-09-17T09:27:09.886Z"),
        publisertTidspunkt: null,
        fullførtTidspunkt: null,
        gyldigTilTidspunkt: new Date("2025-09-18T09:27:09.862Z"),
        harMinstEttResultat: false,
    },
    {
        id: "0ae3094f-ce08-40cd-9185-e55de51fbcd0",
        samarbeidId: 3,
        status: "AVSLUTTET",
        publiseringStatus: "IKKE_PUBLISERT",
        opprettetAv: "X12345",
        type: "BEHOVSVURDERING",
        opprettetTidspunkt: new Date("2025-09-17T09:27:09.815Z"),
        endretTidspunkt: null,
        påbegyntTidspunkt: null,
        publisertTidspunkt: null,
        fullførtTidspunkt: null,
        gyldigTilTidspunkt: new Date("2025-09-18T09:27:09.815Z"),
        harMinstEttResultat: false,
    },
    {
        id: "0ae3094f-ce08-40cd-9185-e55de51fbcd1",
        samarbeidId: 3,
        status: "AVSLUTTET",
        publiseringStatus: "IKKE_PUBLISERT",
        opprettetAv: "X12345",
        type: "EVALUERING",
        opprettetTidspunkt: new Date("2025-09-17T09:27:09.815Z"),
        endretTidspunkt: null,
        påbegyntTidspunkt: null,
        publisertTidspunkt: null,
        fullførtTidspunkt: null,
        gyldigTilTidspunkt: new Date("2025-09-18T09:27:09.815Z"),
        harMinstEttResultat: false,
    },
    {
        id: "1ae3094f-ce08-40cd-9185-e55de51fbcd0",
        samarbeidId: 3,
        status: "OPPRETTET",
        publiseringStatus: "IKKE_PUBLISERT",
        opprettetAv: "X12345",
        type: "BEHOVSVURDERING",
        opprettetTidspunkt: new Date("2025-09-17T09:27:09.815Z"),
        endretTidspunkt: null,
        påbegyntTidspunkt: null,
        publisertTidspunkt: null,
        fullførtTidspunkt: null,
        gyldigTilTidspunkt: new Date("2025-09-18T09:27:09.815Z"),
        harMinstEttResultat: false,
    },
    {
        id: "1ae3094f-ce08-40cd-9185-e55de51fbcd1",
        samarbeidId: 3,
        status: "OPPRETTET",
        publiseringStatus: "IKKE_PUBLISERT",
        opprettetAv: "X12345",
        type: "EVALUERING",
        opprettetTidspunkt: new Date("2025-09-17T09:27:09.815Z"),
        endretTidspunkt: null,
        påbegyntTidspunkt: null,
        publisertTidspunkt: null,
        fullførtTidspunkt: null,
        gyldigTilTidspunkt: new Date("2025-09-18T09:27:09.815Z"),
        harMinstEttResultat: false,
    },
];

export const dummySpørreundersøkelseResultat: SpørreundersøkelseResultat = {
    id: "2f75a5ea-7ad9-46b5-b4e9-37cd167e7958",
    type: "BEHOVSVURDERING",
    spørsmålMedSvarPerTema: [
        {
            id: 19,
            navn: "Partssamarbeid",
            spørsmålMedSvar: [
                {
                    id: "01939c06-422b-7213-930c-4571292085f5",
                    tekst: "Vi planlegger og gjennomfører jevnlige møter i partssamarbeidet",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "01939c07-36be-70f1-b3e3-5ef094f6690c",
                            tekst: "Enig",
                            antallSvar: 0,
                        },
                        {
                            id: "01939c07-526c-73f0-b8a6-f565691ded05",
                            tekst: "Litt enig",
                            antallSvar: 1,
                        },
                        {
                            id: "01939c07-6c97-7964-93d9-0aa0a3a9e734",
                            tekst: "Litt uenig",
                            antallSvar: 0,
                        },
                        {
                            id: "01939c07-a5b3-732d-8e4e-760f6fd475ad",
                            tekst: "Uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "01939c07-c984-7976-a8c8-05778c9635e0",
                            tekst: "Vet ikke",
                            antallSvar: 1,
                        },
                    ],
                    kategori: "Partssamarbeid",
                },
                {
                    id: "01939c0b-21f2-728d-aa91-3c84fef3bb18",
                    tekst: "Hvilke temaer vektlegges mest i møtene?",
                    flervalg: true,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "01939c0b-3ddb-770c-a48b-69df4a902044",
                            tekst: "Lønnsforhandlinger",
                            antallSvar: 0,
                        },
                        {
                            id: "01939c0b-4ccc-72f5-8927-378d67cd6a7a",
                            tekst: "HMS",
                            antallSvar: 0,
                        },
                        {
                            id: "01939c0b-6079-7082-8b94-8457ec89a59d",
                            tekst: "Drift og bemanning",
                            antallSvar: 1,
                        },
                        {
                            id: "01939c0b-7a52-7cbc-a637-8c7dfdbe16f8",
                            tekst: "Sykefravær (f.eks. rutiner, tilrettelegging, oppfølging)",
                            antallSvar: 0,
                        },
                        {
                            id: "01939c0b-939d-7a8a-804e-d95a2dc57d3c",
                            tekst: "Arbeidsmiljø (f.eks. organisering, planlegging)",
                            antallSvar: 1,
                        },
                        {
                            id: "01939c0b-a78b-74f7-9ec0-5203241621cd",
                            tekst: "Personalpolitikk",
                            antallSvar: 1,
                        },
                        {
                            id: "01939c0b-faea-7833-a622-d401d7a75202",
                            tekst: "Velferdsgoder",
                            antallSvar: 0,
                        },
                        {
                            id: "01939c0c-1538-748c-8b7a-c47a4435b959",
                            tekst: "Annet",
                            antallSvar: 0,
                        },
                        {
                            id: "01939c0c-2f3c-77a5-9e83-a6bee6db10e9",
                            tekst: "Vet ikke ",
                            antallSvar: 0,
                        },
                    ],
                    kategori: "Partssamarbeid",
                },
                {
                    id: "01939c14-7280-75a7-aeb6-dcab9e11c906",
                    tekst: "Hvordan opplever du at partssamarbeidet fungerer?",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "01939c14-b530-7469-9ad3-b749339b313b",
                            tekst: "Svært bra",
                            antallSvar: 0,
                        },
                        {
                            id: "01939c14-c972-729f-b17f-92f4960ada31",
                            tekst: "Bra",
                            antallSvar: 2,
                        },
                        {
                            id: "01939c14-dc4c-71cb-b5a1-dd5618d99191",
                            tekst: "Dårlig",
                            antallSvar: 0,
                        },
                        {
                            id: "01939c14-ed0c-70e2-9a9e-ed509fd3c796",
                            tekst: "Svært dårlig",
                            antallSvar: 1,
                        },
                        {
                            id: "01939c14-fbb4-7292-9a3d-32382c9b1d44",
                            tekst: "Vet ikke",
                            antallSvar: 0,
                        },
                    ],
                    kategori: "Partssamarbeid",
                },
                {
                    id: "01939c1a-da7e-7600-ad4e-6d27c5e6fe5a",
                    tekst: "Som leder, tillitsvalgt eller verneombud har jeg god forståelse av min rolle og mine ansvarsområder i partssamarbeidet",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "01939c1b-1fc8-74c7-aba7-2cab04053f4d",
                            tekst: "Enig",
                            antallSvar: 0,
                        },
                        {
                            id: "01939c1b-3124-74e0-b65e-bf5707ceafde",
                            tekst: "Litt enig",
                            antallSvar: 0,
                        },
                        {
                            id: "01939c1b-4074-7c20-b1dd-8833829bf028",
                            tekst: "Litt uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "01939c1b-529d-70a3-b7c6-59be80b6003e",
                            tekst: "Uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "01939c1c-5da9-7988-92b6-006015ab27d8",
                            tekst: "Vet ikke",
                            antallSvar: 1,
                        },
                    ],
                    kategori: "Partssamarbeid",
                },
            ],
        },
        {
            id: 20,
            navn: "Sykefraværsarbeid",
            spørsmålMedSvar: [
                {
                    id: "0193aabd-2eca-787b-922f-8333040f5b0d",
                    tekst: "Vi jobber systematisk for å forebygge sykefravær",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "0193aabd-429f-7daa-bda8-53e97865a9ac",
                            tekst: "Enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aabd-559a-7463-a779-ed9513b9ec04",
                            tekst: "Litt enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aabd-65f9-77a1-bbe8-f3765c3a04f7",
                            tekst: "Litt uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aabd-77c7-777c-b7cd-7c9d7facbbec",
                            tekst: "Uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aabd-9034-753f-b9c0-0b24b571d9f1",
                            tekst: "Vet ikke",
                            antallSvar: 1,
                        },
                    ],
                    kategori: "Sykefraværsarbeid",
                },
                {
                    id: "0193aac0-431c-7bc9-b62b-3bc0617c92ec",
                    tekst: "Vi har sykefraværsrutiner som fungerer godt",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "0193aac0-614f-7399-93ff-af204c983ce4",
                            tekst: "Enig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aac0-6f34-7b69-8754-5d42ce7e9db6",
                            tekst: "Litt enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aac0-83ed-72d0-8346-1a683e2d9be8",
                            tekst: "Litt uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aac0-9bb9-7b8e-ba7c-a3d9b584e262",
                            tekst: "Uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aac0-abe0-7803-a759-c85182f2db52",
                            tekst: "Vet ikke",
                            antallSvar: 0,
                        },
                    ],
                    kategori: "Sykefraværsarbeid",
                },
                {
                    id: "0193aac3-b00b-72e5-ae46-9e546fef3d5f",
                    tekst: "Ansatte kjenner til egne plikter og rettigheter når de er sykmeldt eller står i fare for å bli det",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "0193aac3-c5f7-7db9-b3d9-53cb4c0f6b6a",
                            tekst: "Enig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aac3-d692-7466-9fb5-c1916630b99c",
                            tekst: "Litt enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aac3-f0ef-7993-9146-8445340e4a5e",
                            tekst: "Litt uenig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aac4-04f3-70f2-b449-e7edaa436fdd",
                            tekst: "Uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aac4-4afa-7763-bfb8-f31d63321636",
                            tekst: "Vet ikke",
                            antallSvar: 1,
                        },
                    ],
                    kategori: "Sykefraværsarbeid",
                },
                {
                    id: "0193aac7-72d3-7e26-9846-80cc0f76b292",
                    tekst: "Jeg opplever at ledere er trygge på å følge opp ansatte som er sykmeldt eller står i fare for å bli det",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "0193aac7-8855-7b1e-a0f3-757eb5247c18",
                            tekst: "Enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aac7-9f87-7662-af5f-22028be9b664",
                            tekst: "Litt enig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aac7-b2f5-78a0-9c46-7b71c046fec4",
                            tekst: "Litt uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aac7-c402-76d3-972f-5997d6cc3341",
                            tekst: "Uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aac7-dcf3-70bc-be76-665f697872a7",
                            tekst: "Vet ikke",
                            antallSvar: 0,
                        },
                    ],
                    kategori: "Sykefraværsarbeid",
                },
                {
                    id: "0193aac9-bd28-7d08-a907-f8d09c3b4dca",
                    tekst: "Vi har skriftlig oversikt over tilretteleggingsmuligheter for ansatte",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "0193aac9-cfe3-7b80-b0d6-b688f6ba3347",
                            tekst: "Enig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aac9-dff1-7640-bd72-bd118b50e5e3",
                            tekst: "Litt enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aaca-06ce-71f9-9f84-7c47da37c5f4",
                            tekst: "Litt uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aaca-1908-70f5-bb04-43d119c03d92",
                            tekst: "Uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aaca-3406-7111-97a5-95fd6b809560",
                            tekst: "Vet ikke",
                            antallSvar: 0,
                        },
                    ],
                    kategori: "Sykefraværsarbeid",
                },
                {
                    id: "0193aacc-2675-77eb-8bf3-f3a5de82ad38",
                    tekst: "Tilretteleggingstiltak er midlertidig og avsluttes til avtalt tid",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "0193aacc-391c-7007-9f40-a6a58c68e2b0",
                            tekst: "Enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aacc-47ce-7946-b04c-e44108a7cfcb",
                            tekst: "Litt enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aacc-5a18-71af-a443-831f596c3274",
                            tekst: "Litt uenig",
                            antallSvar: 2,
                        },
                        {
                            id: "0193aacc-695a-7a75-acb3-2d7c9734b5a8",
                            tekst: "Uenig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aacc-785f-7971-93a1-dc4baacb9003",
                            tekst: "Vet ikke",
                            antallSvar: 1,
                        },
                    ],
                    kategori: "Sykefraværsarbeid",
                },
                {
                    id: "0193aacf-95ba-7115-8282-b986f6dbbe86",
                    tekst: "Vi har vanskelige saker som handler om enkeltpersoners sykefravær",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "0193aacf-acaa-7377-a78c-c4a4ff5da529",
                            tekst: "Enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aacf-c3ab-73c3-aeb8-e53f2ab41dd2",
                            tekst: "Litt enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aacf-d4ee-7b49-b473-257b713740a4",
                            tekst: "Litt uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aacf-efb5-76c2-b57d-a0b64d6d47f5",
                            tekst: "Uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aad0-021a-733e-9cdb-8bd5d9958149",
                            tekst: "Vet ikke",
                            antallSvar: 1,
                        },
                    ],
                    kategori: "Sykefraværsarbeid",
                },
            ],
        },
        {
            id: 21,
            navn: "Arbeidsmiljø",
            spørsmålMedSvar: [
                {
                    id: "0193aae2-0875-7e3e-87a5-1ec0f99ae9dc",
                    tekst: "Vi er kjent med de vanlige risikofaktorene i bransjen vår",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "0193aae3-55ce-7833-a589-7222bdb6e961",
                            tekst: "Enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aae3-6b94-76f3-9eb4-e91bea1c7481",
                            tekst: "Litt enig",
                            antallSvar: 2,
                        },
                        {
                            id: "0193aae3-7bbc-7868-9d3d-345f03557ed3",
                            tekst: "Litt uenig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aae3-8f66-7da3-8726-3b6b4ff275f7",
                            tekst: "Uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aae3-b6bb-752e-b284-30ae8522f2e0",
                            tekst: "Vet ikke",
                            antallSvar: 0,
                        },
                    ],
                    kategori: "Arbeidsmiljø",
                },
                {
                    id: "0193aae3-ce58-7124-a054-53e883346e4c",
                    tekst: "Vi har nødvendig kompetanse for å gjøre tiltak for å forbedre arbeidsmiljøet",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "0193aae3-f729-7392-8e45-def38515c51e",
                            tekst: "Enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aae4-0c49-7fb1-8b4a-f162ff68aa6c",
                            tekst: "Litt enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aae4-20a3-7960-88c0-1b6749cc11f8",
                            tekst: "Litt uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aae4-32e0-7bc0-953c-190d8ee71f32",
                            tekst: "Uenig",
                            antallSvar: 2,
                        },
                        {
                            id: "0193aae4-4363-7dc8-8615-c223177b36a1",
                            tekst: "Vet ikke",
                            antallSvar: 0,
                        },
                    ],
                    kategori: "Arbeidsmiljø",
                },
                {
                    id: "0193aae6-355d-7dca-901a-8c9d54033626",
                    tekst: "Vi jobber systematisk med utvikling av arbeidsmiljøet vårt",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "0193aae6-4712-7de8-a55f-aefa8de9d0b3",
                            tekst: "Enig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aae6-5c14-741d-903b-40c85f5d3014",
                            tekst: "Litt enig",
                            antallSvar: 2,
                        },
                        {
                            id: "0193aae6-6ae3-7c27-be4c-50f3f10f7eb8",
                            tekst: "Litt uenig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aae6-7bda-7cc7-916e-5a1481e948ee",
                            tekst: "Uenig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aae6-a154-7b93-9879-4d68f19b2b4a",
                            tekst: "Vet ikke",
                            antallSvar: 0,
                        },
                    ],
                    kategori: "Arbeidsmiljø",
                },
                {
                    id: "0193aae6-b9aa-7ae9-ac0b-4abd3c2c9e70",
                    tekst: "På arbeidsplassen vår blir ansatte med psykiske plager godt ivaretatt",
                    flervalg: false,
                    antallDeltakereSomHarSvart: 3,
                    svarListe: [
                        {
                            id: "0193aae6-d01b-701b-bea6-3f1a3d1d29af",
                            tekst: "Enig",
                            antallSvar: 1,
                        },
                        {
                            id: "0193aae6-e40b-76db-93c0-beac249db061",
                            tekst: "Litt enig",
                            antallSvar: 2,
                        },
                        {
                            id: "0193aae6-f30d-7c8d-8fb5-f0d401d28b32",
                            tekst: "Litt uenig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aae7-0dd1-7d14-aa9d-f050add4972e",
                            tekst: "Uenig",
                            antallSvar: 0,
                        },
                        {
                            id: "0193aae7-252f-76f2-9252-a4b02ad4536d",
                            tekst: "Vet ikke",
                            antallSvar: 0,
                        },
                    ],
                    kategori: "Arbeidsmiljø",
                },
            ],
        },
    ],
};
