name: Build and deploy lydia-radgiver-frontend to labs-gcp
on:
    push:
        branches:
            - deploy-to-labs
env:
    IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
    build:
        name: Build and push labs-specific Docker image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to GitHub Docker Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: ghcr.io/${{ github.repository }}:latest,${{ env.IMAGE }}
                  file: Dockerfile.labs
    deployAppToLabs:
        name: Deploy app to labs
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Deploy to LABS
              uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: labs-gcp
                  RESOURCE: .nais/labs.yaml
