name: Deploy Redis

on:
    push:
        branches:
            - main
        paths:
            - .nais/redis.yaml # Deploy Redis når nais-config endrer seg,
            - .github/workflows/deploy-redis.yaml # og når denne workflowen endrer seg

permissions: {}

jobs:
    deploy-redis:
        strategy:
            matrix:
                cluster: [dev, prod]
        name: Deploy redis to ${{ matrix.cluster }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: ${{ matrix.cluster }}-gcp
                  RESOURCE: .nais/redis.yaml
