name: Deploy Redis

on:
    push:
        branches:
            - main
        paths:
            - ".nais/redis.yaml" # Bare deploy Redis når denne config-filen endrer seg
    workflow_dispatch:

jobs:
    deploy-redis-dev-gcp:
        name: Deploy redis dev-gcp
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: .nais/redis.yaml

    deploy-redis-prod-gcp:
        name: Deploy redis prod-gcp
        needs: deploy-redis-dev-gcp
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: .nais/redis.yaml
