name: Deploy redirect ingresses to dev
run-name: Deploy redirect ingress to dev | ${{ github.event.head_commit.message }}
on:
  push:
    paths:
      - ".github/workflows/deploy-redirect-dev.yaml"
      - ".nais/dev-redirect-fra-intern-til-ansatt.yaml"

permissions:
  id-token: write

jobs:
  deploy:
    name: Deploy redirect ingresses to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy fia redirect ingress to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev-redirect-fra-intern-til-ansatt.yaml
