name: Deploy alerts to NAIS
on:
  push:
    branches:
      - main
    paths:
      - .nais/alerts.yaml
      - .github/workflows/deploy-alerts.yml

permissions:
  id-token: write

jobs:
  apply-alerts:
    strategy:
      matrix:
        cluster: [ dev, prod ]
    name: Deploy alerts to ${{ matrix.cluster }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.1
      - name: Deploy to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v3
        env:
          CLUSTER: ${{ matrix.cluster }}-gcp
          RESOURCE: .nais/alerts.yaml
          VAR: workloadCluster=${{ matrix.cluster }}
