name: Build and deploy lydia-radgiver-frontend
on: [push]

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build:
    name: Build, lint, test and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
      - name: Install deps server
        working-directory: server
        run: npm ci
      - name: Run server tests
        working-directory: server
        run: npm run test
      - name: Install deps client
        working-directory: client
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Run client tests
        working-directory: client
        run: npm run test
      - name: Lint and build frontend
        working-directory: client
        run: npm run build
      - name: Build frackend
        working-directory: server
        run: npm run build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,${{ env.IMAGE }}
          context: .

  deploy:
    strategy:
      matrix:
        cluster: [dev, prod]
    name: Deploy app to ${{ matrix.cluster }}
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/${{ matrix.cluster }}.yaml


  deploy-to-dev:
    strategy:
      matrix:
        cluster: [dev]
    name: Deploy app to ${{ matrix.cluster }}
    needs: build
    if: github.ref == 'refs/heads/csrf_rewrite'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/${{ matrix.cluster }}.yaml
